apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app
        image: 682475225405.dkr.ecr.us-east-1.amazonaws.com/java-maven-app:1.2
        ports:
        - containerPort: 8080
        env:
        - name: DB_SERVER
          value: mysql-db
        - name: DB_NAME
          value: myappdb
        - name: DB_USER
          value: myuser
        - name: DB_PASSWORD
          value: mypassword
---
apiVersion: v1
kind: Service
metadata:
  name: spring-app
spec:
  selector:
    app: spring-app
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer

